version: 2
environment:
  YARN_VERSION: 1.0.0
jobs:
  build:
    environment:
      PATH: /root/.yarn/bin:/usr/local/bin:/usr/bin:/bin
      YARN_VERSION: 0.20.3
    docker:
      - image: node:6.10.0
    working_directory: ~/baberutv
    steps:
      - checkout
      - restore_cache:
          key: baberutv-yarn-{{ .Branch }}
      - run:
          name: Install Yarn
          command: |
            if [[ ! -n $(which yarn) || $(yarn --version) != "${YARN_VERSION}" ]]; then
              echo "Download and install Yarn."
              curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION}
            else
              echo "The correct version of Yarn is already installed."
            fi
      - save_cache:
          key: baberutv-yarn-{{ .Branch }}
          paths:
            - ~/.yarn
      - restore_cache:
          key: baberutv-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: baberutv-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Post-Test
          command: cat ./coverage/lcov.info | $(yarn bin)/coveralls || echo "1"
      - deploy:
          command: |
            if echo $(git describe) | grep -Eq "^v[[:digit:]](\\.[[:digit:]]+)*$"; then
              ./scripts/deploy.sh
            fi
